## Server properties
server:
  port: 8080

## Primary/Target Database Properties
#Target1 (Mysql)
spring:
  datasource:
#    url: jdbc:mysql://172.16.3.124:3304/memberdb #kic
    url: jdbc:mysql://localhost:3304/memberdb #local
    username: root
    password: root
#  jpa.hibernate.ddl-auto: create
  jpa.show-sql: true
#Target2 (Oracle)
datasource:
  url: jdbc:oracle:thin:@orademoapt?TNS_ADMIN=$ORACLE_WALLET
  username: admin
  password: KTgLi-$sgZbj36n
  driver-class-name: oracle.jdbc.driver.OracleDriver

## Source Database Properties
source:
  datasource:
#    host: 172.16.3.124 #kic
    host: localhost #local
    port: 3305
    database: memberdb
    username: root
    password: root

  ## Logging properties
logging:
  level:
    root: INFO
    io:
      debezium:
        mysql:
          BinlogReader: INFO
    com:
      example:
        debeziumproject: DEBUG
