## Server properties
server:
  port: 8080

## Primary/Target Database Properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3304/memberdb
    username: root
    password: root
#  jpa.hibernate.ddl-auto: create
  jpa.show-sql: true

## Source Database Properties
customer:
  datasource:
    host: localhost
    port: 3305
    database: memberdb
    username: root
    password: root

  ## Logging properties
logging:
  level:
    root: INFO
    io:
      debezium:
        mysql:
          BinlogReader: INFO
    com:
      example:
        debeziumproject: DEBUG